import "./globals.css";
import { Inter } from "next/font/google";

import "@fontsource/monoton";
import "@fontsource/cutive";
import "@fontsource/noto-serif";

import Link from "next/link";

export const metadata = {
  title: "Ayush Bhargava",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-eggshell">
        <div className="flex flex-col items-center min-h-screen mx-8 md:mx-4">
          <div className="max-w-screen-lg w-full flex items-center justify-between my-8 ">
            <Link href={"/"} className="logo">
              Ayush
            </Link>
            <div className="flex-row flex">
              <Link href={"/projects"}>
                <p className="mr-4 md:mr-8"> Projects</p>
              </Link>
              <Link href={"/experience"}>
                <p>Experience</p>
              </Link>
            </div>
          </div>

          {children}
        </div>
        <div className="bg-navy justify-center items-center flex">
          <div className="h-12 flex justify-between items-center bottom-0 max-w-screen-lg flex-1">
            <div className="flex ">
              <Link href={"https://www.linkedin.com/in/ayushbharg"} target="_blank">
                <img src="/linkedinIcon.svg" alt="logo" className="h-6 ml-4" />
              </Link>
              <Link href={"https://github.com/ayushbh2020"} target="_blank">
                <img src="/githubIcon.svg" alt="logo" className="h-6 ml-4" />
              </Link>
            </div>
            <p className="mr-4 text-xs text-white text-right">Made with ❤ in Canada </p>
          </div>
        </div>
      </body>
    </html>
  );
}
